### ISSUE TITLE
Public box on hashicorp has hardcoded serial port file

### ISSUE THREAD

**Issue by isharacomix** [Cyclid/Vagrant#3]
When following the instructions here, http://docs.cyclid.io/en/latest/vagrant.html , the image fails to boot.

The OVA that was uploaded to hashicorp has a hardcoded URL for Serial Port one: `/Users/kristian/Cyclid/Source/Vagrant/ubuntu-xenial-16.04-cloudimg-console.log` - when I override the serial commands in the vagrantfile as such, it boots perfectly.

```
        config.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
            vbox.customize ["modifyvm", :id, "--uartmode1", "tcpserver", "4001$
        end
```

**Comment by Vanders** [comment]
That's annoying; it comes from the Ubuntu Xenial box used as the base. It's odd that it then becomes a hard-coded path when the Cyclid box is packaged, but that seems to be a Virtualbox/Vagrant bug (or possibly even working by Machiavellian design).

The serial console log is entirely unexciting anyway, so I think the best solution is to override the UART settings and just disable & disconnect UART1 so that nothing is produced; individual users can always re-enable it again in _their_ Vagrantfile if they really, really, want a serial console.

**Comment by Vanders** [comment]
This should be fixed by https://github.com/Cyclid/Vagrant/blob/master/Vagrantfile#L12

I've rebuilt the box & updated version v0.2.4 on Atlas; if you'd like to give it a try, delete your old box first:
`vagrant box remove Liqwyd/Cyclid`
and then
`vagrant up`
should download & boot the updated version without any intervention from you.
